research_news_task:
  description: >
    Conduct thorough research about {topic}.
    Find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

research_paper_task:
  description: >
    Research recent academic papers and developments about {topic}.
    Focus on breakthrough findings and significant advancements.
  expected_output: >
    A summary of key research papers and developments in {topic}
  agent: researcher

write_newsletter_task:
  description: >
    Create an engaging newsletter based on the research findings.
    Make it informative yet accessible to a general audience.
  expected_output: >
    A well-structured newsletter draft about {topic}
  agent: editor

review_newsletter_task:
  description: >
    Review the newsletter draft for accuracy, clarity, and engagement.
    Ensure it meets our quality standards.
  expected_output: >
    The final version of the newsletter, ready for distribution
  agent: reviewer
  output_file: newsletter.md